variables:
  IMAGE_NAME: obar-backend
  IMAGE_TAG: latest
  ECR_REGISTRY: 510481412586.dkr.ecr.eu-central-1.amazonaws.com

build_image:
  stage: build
  image: docker:20.10.16
  services:
    - docker:20.10.16-dind
  variables:
    DOCKER_TLS_CERTDIR: "/certs"
  before_script:
    - aws ecr $AWS_ACCESS_KEY_ID:$AWS_SECRET_ACCESS_KEY | docker login --username AWS --password-stdin $ECR_REGISTRY
  script:
    - docker build -t $ECR_REGISTRY/$IMAGE_NAME:$IMAGE_TAG .
    - docker push $ECR_REGISTRY/$IMAGE_NAME:$IMAGE_TAG
