variables:
  IMAGE_NAME: obar-backend
  IMAGE_TAG: latest
  ECR_REGISTRY: public.ecr.aws/m4g5m4m1/obar-backend

build_image:
  stage: build
  image: docker:20.10.16
  services:
    - docker:20.10.16-dind
  variables:
    DOCKER_TLS_CERTDIR: "/certs"
  before_script:
    - echo $AWS_ACCESS_KEY_ID:$AWS_SECRET_ACCESS_KEY | docker login --username AWS --password-stdin $ECR_REGISTRY
  script:
    - docker build -t $ECR_REGISTRY/$IMAGE_NAME:$IMAGE_TAG .
    - docker push $ECR_REGISTRY/$IMAGE_NAME:$IMAGE_TAG