stages:
  - deploy

variables:
  ECR_REGISTRY: $ECR_REGISTRY
  IMAGE_NAME: "oceanbar-be"
  AWS_REGION: "eu-central-1"

deploy:
  stage: deploy
  script:
    - echo "Deploying to ECR"
    - export TAG=$(date '+%Y%m%d%H%M%S')
    - echo $CI_REGISTRY_IMAGE:$TAG
    - echo $AWS_SECRET_ACCESS_KEY | aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $ECR_REGISTRY
    - docker build -t $ECR_REGISTRY/$IMAGE_NAME:$TAG .
    - docker push $ECR_REGISTRY/$IMAGE_NAME:$TAG
  only:
    - main