variables:
  DOCKER_REGISTRY: public.ecr.aws/m4g5m4m1
  APP_NAME: obar-backend
  TAG: latest

stages:
  - build
  - build-docker-image
  - push-image-to-aws-ecr

build:
  stage: build
  image: node:14
  script:
    - npm install
    - npm run build
  artifacts:
    paths:
      - /app/dist/

build-docker-image:
  stage: build-docker-image
  image: docker:20.10
  services:
    - docker:dind
  script:
    - docker info
    - docker build -t $APP_NAME .
    - docker tag $APP_NAME:latest $DOCKER_REGISTRY/$APP_NAME:$TAG

push-image-to-aws-ecr:
  stage: push-image-to-aws-ecr
  image:
    name: amazon/aws-cli
    entrypoint: [""]
  before_script:
    - amazon-linux-extras install -y docker
    - aws --version
    - docker --version
  script:
    - aws ecr-public get-login-password --region us-east-1 | docker login --username AWS --password-stdin $DOCKER_REGISTRY
    - docker push $DOCKER_REGISTRY/$APP_NAME:$TAG