variables:
  DOCKER_REGISTRY: 510481412586.dkr.ecr.eu-central-1.amazonaws.com
  APP_NAME: obar-backend
  TAG: "$CI_COMMIT_SHORT_SHA-$CI_PIPELINE_ID"

stages:
  - build
  - build-docker-image
  - push-image-to-aws-ecr

build-project:
  stage: build
  script:
    - npm install
    - npm run build  
  artifacts:
    paths:
      - /app/dist/  
build-docker-image:
  stage: build-docker-image
  script:
    - docker info
    - docker build -t $DOCKER_REGISTRY/$APP_NAME:"$TAG" .

push-image-to-aws-ecr:
  stage: push-image-to-aws-ecr
  image:
    name: $DOCKER_REGISTRY/$APP_NAME:"$TAG"
  services:
    - docker:dind
  script:
    - aws ecr get-login-password --region eu-central-1 | docker login --username AWS --password-stdin $DOCKER_REGISTRY
    - docker tag $DOCKER_REGISTRY/$APP_NAME:"$TAG" $DOCKER_REGISTRY/$APP_NAME:"$TAG"
    - docker push $DOCKER_REGISTRY/$APP_NAME:"$TAG"
