variables:
  DOCKER_REGISTRY: 510481412586.dkr.ecr.eu-central-1.amazonaws.com
  APP_NAME: obar-backend
  AWS_DEFAULT_REGION: eu-central-1
  TAG: latest
  
stages:
  - build
  - build-docker-image
  - push-image-to-aws-ecr
  
build:
  stage: build
  image: node:16
  script:
    - npm install
    - npm run build
  artifacts:
    paths:
      - /app/dist/

build-docker-image:
  stage: build-docker-image
  image: docker:latest
  services:
    - docker:dind   
  before_script:
    - apk add --no-cache curl jq python3 py3-pip     
  script:
    - docker build -t $APP_NAME .
    - docker tag obar-backend:latest 510481412586.dkr.ecr.eu-central-1.amazonaws.com/obar-backend:latest 
    
push-image-to-aws-ecr:
  stage: push-image-to-aws-ecr
  image:
    name: amazon/aws-cli
    entrypoint: [""]
  services:
    - name: docker:dind
  before_script:   
    - amazon-linux-extras install -y docker
    - aws --version
    - docker --version
    - aws ecr get-login-password --region eu-central-1 | docker login --username AWS --password-stdin 510481412586.dkr.ecr.eu-central-1.amazonaws.com 
  script:
    - echo "Pushing image to ECR..."
    - docker push 510481412586.dkr.ecr.eu-central-1.amazonaws.com\obar-backend:latest    
